__DS_challenge_1__

In [2]:
!ls /home/dsc/Data/challenge

bookings.csv.bz2  searches.csv.bz2

In [3]:
!bzcat /home/dsc/Data/challenge/bookings.csv.bz2 | head -10000 >> bookings.sample.csv

bzcat: I/O or other error, bailing out.  Possible reason follows.
bzcat: Broken pipe
	Input file = /home/dsc/Data/challenge/bookings.csv.bz2, output file = (stdout)

In [4]:
!bzip2 -f bookings.sample.csv

In [5]:
!ls -l

total 592
-rw-rw-r-- 1 dsc dsc 535893 nov 20 19:59  bookings.sample.csv.bz2
-rw-rw-r-- 1 dsc dsc  61282 nov 20 19:33 'Ex_1_&_2.ipynb'
-rw-rw-r-- 1 dsc dsc    964 nov 20 18:06  Ex_2.ipynb
-rw-rw-r-- 1 dsc dsc     72 nov 20 17:17  README.md

In [6]:
!bzcat bookings.sample.csv.bz2 | wc -l

10000

With Python

In [7]:
import bz2

fileBz2 = bz2.BZ2File('./bookings.sample.csv.bz2')
type(fileBz2)

bz2.BZ2File

In [8]:
k = 0
for line in fileBz2:
    k += 1
    
print(k)

10000

Or

In [9]:
with bz2.BZ2File('./bookings.sample.csv.bz2') as fileBz2:
    k = 0
    for line in fileBz2:
        k += 1
        
print(k)

10000

This method close the file at the end

In [10]:
fileBz2.closed

True

In [11]:
with bz2.BZ2File('./bookings.sample.csv.bz2') as fileBz2:
    k = 0
    for line in fileBz2:
        k += 1
        if k == 1000:
            break
print(k)

1000

__Exercise 2__

In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('./bookings.sample.csv.bz2', compression = 'bz2', sep = '^')
df.shape

(9999, 38)

In [15]:
df.columns

Index(['act_date           ', 'source', 'pos_ctry', 'pos_iata', 'pos_oid  ',
       'rloc          ', 'cre_date           ', 'duration', 'distance',
       'dep_port', 'dep_city', 'dep_ctry', 'arr_port', 'arr_city', 'arr_ctry',
       'lst_port', 'lst_city', 'lst_ctry', 'brd_port', 'brd_city', 'brd_ctry',
       'off_port', 'off_city', 'off_ctry', 'mkt_port', 'mkt_city', 'mkt_ctry',
       'intl', 'route          ', 'carrier', 'bkg_class', 'cab_class',
       'brd_time           ', 'off_time           ', 'pax', 'year', 'month',
       'oid      '],
      dtype='object')

In [16]:
len(df['rloc          '].unique())

3638

In [17]:
df['arr_port'].unique()

array(['LHR     ', 'CLT     ', 'SVO     ', 'LGA     ', 'SIN     ',
       'TUS     ', 'CTA     ', 'YWG     ', 'PVG     ', 'SGC     ',
       'ALG     ', 'DMM     ', 'LED     ', 'LIS     ', 'BLR     ',
       'BWI     ', 'DEL     ', 'TPA     ', 'MNL     ', 'ULN     ',
       'ZRH     ', 'ALA     ', 'FCO     ', 'AYT     ', 'MVD     ',
       'CVG     ', 'OTP     ', 'CDG     ', 'HAV     ', 'NRT     ',
       'BKK     ', 'MEX     ', 'SAV     ', 'EWR     ', 'SFO     ',
       'DTW     ', 'OMA     ', 'YVR     ', 'ACC     ', 'SDF     ',
       'CAI     ', 'TLV     ', 'ELP     ', 'HMO     ', 'LAS     ',
       'BOI     ', 'TYR     ', 'ATL     ', 'IST     ', 'BBI     ',
       'ISB     ', 'LCA     ', 'FRA     ', 'CAG     ', 'DCA     ',
       'COS     ', 'SHA     ', 'DAY     ', 'MCO     ', 'BOS     ',
       'TIA     ', 'SKG     ', 'LCY     ', 'SJD     ', 'DFW     ',
       'LAX     ', 'ADD     ', 'PHX     ', 'LIR     ', 'SYD     ',
       'MIA     ', 'MCI     ', 'YHZ     ', 'STL     ', 'OGG     ',
       'HKG     ', 'TXL     ', 'WAW     ', 'LYR     ', 'MRS     ',
       'IXE     ', 'BRU     ', 'MQN     ', 'JED     ', 'GAU     ',
       'FAI     ', 'SJU     ', 'MUC     ', 'LIT     ', 'PDX     ',
       'SXM     ', 'JAC     ', 'ATH     ', 'DOH     ', 'BCN     ',
       'FAO     ', 'CCJ     ', 'CGK     ', 'COK     ', 'YUL     ',
       'BNE     ', 'GUM     ', 'DXB     ', 'CCS     ', 'RUH     ',
       'BUF     ', 'KIV     ', 'CZM     ', 'BNA     ', 'SGN     ',
       'AUS     ', 'AGP     ', 'ORD     ', 'ORY     ', 'SNA     ',
       'BEY     ', 'VPS     ', 'CUR     ', 'PBI     ', 'SDU     ',
       'ANC     ', 'DEN     ', 'UVF     ', 'HNL     ', 'KUL     ',
       'BRD     ', 'MAD     ', 'NAS     ', 'MSY     ', 'MEL     ',
       'AMS     ', 'BHM     ', 'SOF     ', 'ICN     ', 'WDH     ',
       'LIM     ', 'REN     ', 'SVQ     ', 'MAN     ', 'TLS     ',
       'NBO     ', 'ASU     ', 'MED     ', 'GRU     ', 'CUN     ',
       'CUZ     ', 'BOM     ', 'MSO     ', 'SAN     ', 'CHQ     ',
       'JFK     ', 'PHL     ', 'BOG     ', 'YXE     ', 'SAT     ',
       'MDZ     ', 'MLX     ', 'ISU     ', 'LAO     ', 'SSA     ',
       'FUE     ', 'DAC     ', 'LIN     ', 'CBR     ', 'YYZ     ',
       'FLL     ', 'BJV     ', 'MAA     ', 'BLQ     ', 'VVI     ',
       'CAN     ', 'AMD     ', 'AUH     ', 'CMB     ', 'SMI     ',
       'IND     ', 'LOS     ', 'DAB     ', 'OAK     ', 'ATQ     ',
       'EZE     ', 'MGW     ', 'MCT     ', 'KHI     ', 'WRO     ',
       'GIZ     ', 'YNB     ', 'SHV     ', 'HER     ', 'ALC     ',
       'SDQ     ', 'RAK     ', 'BUD     ', 'YYC     ', 'JNB     ',
       'JAX     ', 'PVR     ', 'BJX     ', 'SJO     ', 'MSN     ',
       'MEM     ', 'TPE     ', 'PIT     ', 'CUL     ', 'JKH     ',
       'CRK     ', 'KOA     ', 'DPS     ', 'MHT     ', 'SLC     ',
       'YAY     ', 'RAI     ', 'AKL     ', 'RDU     ', 'FDH     ',
       'AXM     ', 'GUA     ', 'DZA     ', 'LGW     ', 'HAM     ',
       'ORN     ', 'QOW     ', 'DKR     ', 'KLX     ', 'GVA     ',
       'DUB     ', 'BIQ     ', 'RTB     ', 'HDY     ', 'UIO     ',
       'ERI     ', 'CMN     ', 'LSE     ', 'ALB     ', 'SJC     ',
       'YCD     ', 'SNN     ', 'PER     ', 'PSA     ', 'ROV     ',
       'MXP     ', 'RIC     ', 'ROA     ', 'BHX     ', 'CGN     ',
       'BGO     ', 'FLR     ', 'DUR     ', 'IDR     ', 'BFN     ',
       'AJF     ', 'ARH     ', 'SMF     ', 'SRQ     ', 'DUS     ',
       'HYD     ', 'PUJ     ', 'BJA     ', 'KIN     ', 'POS     ',
       'IAS     ', 'IAH     ', 'ISN     ', 'AVL     ', 'SEA     ',
       'EBL     ', 'TAO     ', 'OAJ     ', 'GYE     ', 'PEW     ',
       'SVG     ', 'PAP     ', 'ABQ     ', 'STT     ', 'ASE     ',
       'SPS     ', 'MBJ     ', 'ASW     ', 'DAL     ', 'KSN     ',
       'IAD     ', 'AES     ', 'AMM     ', 'CAK     ', 'ARN     ',
       'TIP     ', 'IXC     ', 'MME     ', 'ESB     ', 'AEP     ',
       'CMH     ', 'PSP     ', 'MKE     ', 'NCE     ', 'IQQ     ',
       'DLA     ', 'EWN     ', 'JLN     ', 'CPH     ', 'KBP     ',
       'AER     ', 'AGA     ', 'CTG     ', 'RBA     ', 'LHE     ',
       'HBE     ', 'PAD     ', 'TRD     ', 'GOT     ', 'PRG     ',
       'MIR     ', 'CID     ', 'CEB     ', 'CJS     ', 'GEO     ',
       'RUN     ', 'MDE     ', 'PNH     ', 'HEL     ', 'CLO     ',
       'TFN     ', 'PEK     ', 'GRB     ', 'CGO     ', 'CCP     ',
       'NTE     ', 'RKS     ', 'ZYL     ', 'HKT     ', 'USM     ',
       'FAR     ', 'GEG     ', 'CNS     ', 'GSP     ', 'SZX     ',
       'ZNZ     ', 'JRO     ', 'NAP     ', 'BRI     ', 'JNU     ',
       'KWI     ', 'PRI     ', 'CEK     ', 'KIX     ', 'HAJ     ',
       'OKC     ', 'XNA     ', 'MYR     ', 'YQM     ', 'PIA     ',
       'FCA     ', 'LTN     ', 'SUF     ', 'PBM     ', 'TSR     ',
       'LCG     ', 'GRR     ', 'YXY     ', 'HUX     ', 'HGH     ',
       'GDL     ', 'RHO     ', 'RNO     ', 'PLZ     ', 'DME     ',
       'TYS     ', 'ROC     ', 'GMP     ', 'TMP     ', 'VNO     ',
       'KTM     ', 'QJZ     ', 'SCL     ', 'BCD     ', 'YQU     ',
       'YZF     ', 'MLI     ', 'MSP     ', 'CFE     ', 'BUR     ',
       'RSW     ', 'KGS     ', 'GTF     ', 'HAN     ', 'SGF     ',
       'MID     ', 'LIH     ', 'YYJ     ', 'LPA     ', 'TGD     ',
       'RPR     ', 'VCE     ', 'ABV     ', 'CNX     ', 'MAF     ',
       'TNR     ', 'OVB     ', 'PTP     ', 'TGU     ', 'DRW     ',
       'TSA     ', 'MOB     ', 'MKG     ', 'GDN     ', 'GLA     ',
       'MGA     ', 'ABZ     ', 'PUS     ', 'BQK     ', 'BGI     ',
       'TUN     ', 'VIE     ', 'BPS     ', 'CLE     ', 'AUA     ',
       'YEG     ', 'YOW     ', 'FSP     ', 'GFK     ', 'RGN     ',
       'GPT     ', 'BLL     ', 'LRT     ', 'PLS     ', 'MPM     ',
       'BRW     ', 'GNV     ', 'TBS     ', 'EAS     ', 'AQP     ',
       'KGD     ', 'CPR     ', 'EZS     ', 'OMS     ', 'LKO     ',
       'CHS     ', 'JST     ', 'AAL     ', 'CLJ     ', 'PLQ     ',
       'ONT     ', 'RAJ     ', 'ANF     ', 'AJA     ', 'CUC     ',
       'PMI     ', 'OAG     ', 'LUG     ', 'HFE     ', 'ORF     ',
       'JJN     ', 'ECP     ', 'SBP     ', 'MAR     ', 'BTR     ',
       'JDH     ', 'RAP     ', 'FUK     ', 'BHH     ', 'MLA     ',
       'MBA     ', 'FLO     ', 'MDW     ', 'SOM     ', 'VKO     ',
       'SZG     ', 'ICT     ', 'FAT     ', 'FOC     ', 'MLB     ',
       'BAH     ', 'VER     ', 'SOU     ', 'PMC     ', 'VTZ     ',
       'VLC     ', 'MDT     ', 'EDI     ', 'AOE     ', 'OPO     ',
       'FNC     ', 'TUL     ', 'SAP     ', 'KRK     ', 'OSL     ',
       'MLE     ', 'YVO     ', 'YHD     ', 'YQT     ', 'YMM     ',
       'YQQ     ', 'IXZ     ', 'GOJ     ', 'THR     ', 'AOI     ',
       'SSH     ', 'BZE     ', 'AGU     ', 'IBZ     ', 'BLJ     ',
       'FIH     ', 'HPN     ', 'ATW     ', 'PNA     ', 'CTS     ',
       'PAT     ', 'IKA     ', 'MRY     ', 'BGA     ', 'IGU     ',
       'WLG     ', 'PDL     ', 'BEG     ', 'BRE     ', 'NOS     ',
       'DIE     ', 'HRK     ', 'COR     ', 'PTY     ', 'LUO     ',
       'NSI     ', 'BDA     ', 'FLN     ', 'GOA     ', 'MAO     ',
       'GIG     ', 'BTM     ', 'SYR     ', 'GCC     ', 'GCM     ',
       'BDL     ', 'FSD     ', 'KBL     ', 'WUH     ', 'AGX     ',
       'JAN     ', 'FNA     ', 'LYS     ', 'SBA     ', 'MSU     ',
       'POL     ', 'TCQ     ', 'VNS     ', 'CRW     ', 'ANU     ',
       'TRN     ', 'SKP     ', 'LFT     ', 'RFP     ', 'PVD     ',
       'TOS     ', 'MSQ     ', 'YXS     ', 'SPU     ', 'HLA     ',
       'EVN     ', 'LIL     ', 'BOD     ', 'JYV     ', 'DSM     ',
       'SXF     ', 'CPT     ', 'SPN     ', 'BKI     ', 'GZP     ',
       'HRG     ', 'CCU     ', 'LIG     ', 'MTY     ', 'KWL     ',
       'AVP     ', 'FAY     ', 'LJU     ', 'KSM     ', 'SJJ     ',
       'KYA     ', 'NAN     ', 'CTU     ', 'CSG     ', 'ZAG     ',
       'SDR     ', 'MRV     ', 'TNG     ', 'NUE     ', 'MFR     ',
       'BTV     ', 'PMO     ', 'CHA     ', 'NBC     ', 'ILM     ',
       'SXB     ', 'SYZ     ', 'WEH     ', 'PRN     ', 'XMN     ',
       'TRW     ', 'ORK     ', 'OSR     ', 'FWA     ', 'KGI     ',
       'FOR     ', 'LEX     ', 'IVL     ', 'ECN     ', 'STN     ',
       'OME     ', 'MTR     ', 'BWN     ', 'BME     ', 'DRS     ',
       'IXB     ', 'BIO     ', 'SAL     ', 'GYD     ', 'HOU     ',
       'BSL     ', 'HAK     ', 'AFA     ', 'VSA     ', 'CHC     ',
       'TOF     ', 'STS     ', 'ITM     ', 'XNB     ', 'OUD     ',
       'KEF     ', 'TRV     ', 'OKA     ', 'HBA     ', 'UBP     ',
       'NAG     ', 'PPT     ', 'LGB     ', 'LBV     ', 'ADZ     ',
       'IKT     ', 'NGB     ', 'SLL     ', 'UKK     ', 'QQS     ',
       'NPL     ', 'BRC     ', 'FPO     ', 'USH     ', 'TFS     ',
       'PEI     ', 'CRL     ', 'SIP     ', 'SCQ     ', 'RST     ',
       'FRU     ', 'ROB     ', 'BRM     ', 'HHH     ', 'YTM     ',
       'KTN     ', 'DBV     ', 'EYW     ', 'TLH     ', 'NCL     ',
       'MRU     ', 'XQP     ', 'SBZ     '], dtype=object)

In [19]:
df.groupby['arr_port']

TypeError: 'method' object is not subscriptable

In [134]:
chunk_size=100000
reader = pd.read_csv('/home/dsc/Data/challenge/bookings.csv.bz2',chunksize = chunk_size, compression = 'bz2',  sep='^', iterator=True)
chunks = []

k = 0
for df in reader:
    chunks.append(df.groupby('arr_city').agg({"pax": "sum"}))
    k+=1
    print(k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50

/home/dsc/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (7,8,27) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101

In [135]:
chunks

[          pax
 arr_city
 AAE         2
 AAL        16
 AAQ         5
 AAR         4
 ABE        16
 ...       ...
 ZRH       301
 ZSH         2
 ZTH         0
 ZUH         3
 ZYL        17

 [1446 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11
 ...       ...
 ZOS         2
 ZQN        23
 ZRH       147
 ZSE         3
 ZYL        23

 [1424 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        12
 AAQ        12
 AAR         6
 ABA         1
 ...       ...
 ZSE        -2
 ZSH         4
 ZTH         2
 ZUH         1
 ZYL         8

 [1474 rows x 1 columns],           pax
 arr_city
 AAE         8
 AAH         2
 AAL         4
 AAQ         5
 AAR         3
 ...       ...
 ZSA         1
 ZSH         6
 ZTH         0
 ZVK        -1
 ZYL        37

 [1483 rows x 1 columns],           pax
 arr_city
 AAE        23
 AAL         7
 AAQ         8
 AAR         9
 ABE         8
 ...       ...
 ZQN        28
 ZRH       151
 ZSH         4
 ZUH         0
 ZYL        11

 [1499 rows x 1 columns],           pax
 arr_city
 AAE        17
 AAL         5
 AAQ        11
 AAR        -1
 ABA         1
 ...       ...
 ZQN        10
 ZRH       205
 ZSH         6
 ZVK         2
 ZYL        -3

 [1498 rows x 1 columns],           pax
 arr_city
 AAE         7
 AAL        14
 AAN         2
 AAQ         3
 AAR         4
 ...       ...
 ZQN        13
 ZRH       227
 ZSH         2
 ZTH         0
 ZYL        16

 [1511 rows x 1 columns],           pax
 arr_city
 AAE        11
 AAL        20
 AAQ         7
 AAR         0
 ABE         4
 ...       ...
 ZQN        11
 ZRH       242
 ZSH         4
 ZTH         1
 ZYL        11

 [1471 rows x 1 columns],           pax
 arr_city
 AAB         3
 AAE         7
 AAL        17
 AAQ        10
 AAR         4
 ...       ...
 ZQN        10
 ZRH       189
 ZSH         2
 ZTH         2
 ZYL        -7

 [1491 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        16
 AAQ         5
 AAR         4
 ABE        16
 ...       ...
 ZRH       301
 ZSH         2
 ZTH         0
 ZUH         3
 ZYL        17

 [1446 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11
 ...       ...
 ZOS         2
 ZQN        23
 ZRH       147
 ZSE         3
 ZYL        23

 [1424 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        12
 AAQ        12
 AAR         6
 ABA         1
 ...       ...
 ZSE        -2
 ZSH         4
 ZTH         2
 ZUH         1
 ZYL         8

 [1474 rows x 1 columns],           pax
 arr_city
 AAE         8
 AAH         2
 AAL         4
 AAQ         5
 AAR         3
 ...       ...
 ZSA         1
 ZSH         6
 ZTH         0
 ZVK        -1
 ZYL        37

 [1483 rows x 1 columns],           pax
 arr_city
 AAE        23
 AAL         7
 AAQ         8
 AAR         9
 ABE         8
 ...       ...
 ZQN        28
 ZRH       151
 ZSH         4
 ZUH         0
 ZYL        11

 [1499 rows x 1 columns],           pax
 arr_city
 AAE        17
 AAL         5
 AAQ        11
 AAR        -1
 ABA         1
 ...       ...
 ZQN        10
 ZRH       205
 ZSH         6
 ZVK         2
 ZYL        -3

 [1498 rows x 1 columns],           pax
 arr_city
 AAE         7
 AAL        14
 AAN         2
 AAQ         3
 AAR         4
 ...       ...
 ZQN        13
 ZRH       227
 ZSH         2
 ZTH         0
 ZYL        16

 [1511 rows x 1 columns],           pax
 arr_city
 AAE        11
 AAL        20
 AAQ         7
 AAR         0
 ABE         4
 ...       ...
 ZQN        11
 ZRH       242
 ZSH         4
 ZTH         1
 ZYL        11

 [1471 rows x 1 columns],           pax
 arr_city
 AAB         3
 AAE         7
 AAL        17
 AAQ        10
 AAR         4
 ...       ...
 ZQN        10
 ZRH       189
 ZSH         2
 ZTH         2
 ZYL        -7

 [1491 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        16
 AAQ         5
 AAR         4
 ABE        16
 ...       ...
 ZRH       301
 ZSH         2
 ZTH         0
 ZUH         3
 ZYL        17

 [1446 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11
 ...       ...
 ZOS         2
 ZQN        23
 ZRH       147
 ZSE         3
 ZYL        23

 [1424 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        12
 AAQ        12
 AAR         6
 ABA         1
 ...       ...
 ZSE        -2
 ZSH         4
 ZTH         2
 ZUH         1
 ZYL         8

 [1474 rows x 1 columns],           pax
 arr_city
 AAE         8
 AAH         2
 AAL         4
 AAQ         5
 AAR         3
 ...       ...
 ZSA         1
 ZSH         6
 ZTH         0
 ZVK        -1
 ZYL        37

 [1483 rows x 1 columns],           pax
 arr_city
 AAE        23
 AAL         7
 AAQ         8
 AAR         9
 ABE         8
 ...       ...
 ZQN        28
 ZRH       151
 ZSH         4
 ZUH         0
 ZYL        11

 [1499 rows x 1 columns],           pax
 arr_city
 AAE        17
 AAL         5
 AAQ        11
 AAR        -1
 ABA         1
 ...       ...
 ZQN        10
 ZRH       205
 ZSH         6
 ZVK         2
 ZYL        -3

 [1498 rows x 1 columns],           pax
 arr_city
 AAE         7
 AAL        14
 AAN         2
 AAQ         3
 AAR         4
 ...       ...
 ZQN        13
 ZRH       227
 ZSH         2
 ZTH         0
 ZYL        16

 [1511 rows x 1 columns],           pax
 arr_city
 AAE        11
 AAL        20
 AAQ         7
 AAR         0
 ABE         4
 ...       ...
 ZQN        11
 ZRH       242
 ZSH         4
 ZTH         1
 ZYL        11

 [1471 rows x 1 columns],           pax
 arr_city
 AAB         3
 AAE         7
 AAL        17
 AAQ        10
 AAR         4
 ...       ...
 ZQN        10
 ZRH       189
 ZSH         2
 ZTH         2
 ZYL        -7

 [1491 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        16
 AAQ         5
 AAR         4
 ABE        16
 ...       ...
 ZRH       301
 ZSH         2
 ZTH         0
 ZUH         3
 ZYL        17

 [1446 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11
 ...       ...
 ZOS         2
 ZQN        23
 ZRH       147
 ZSE         3
 ZYL        23

 [1424 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        12
 AAQ        12
 AAR         6
 ABA         1
 ...       ...
 ZSE        -2
 ZSH         4
 ZTH         2
 ZUH         1
 ZYL         8

 [1474 rows x 1 columns],           pax
 arr_city
 AAE         8
 AAH         2
 AAL         4
 AAQ         5
 AAR         3
 ...       ...
 ZSA         1
 ZSH         6
 ZTH         0
 ZVK        -1
 ZYL        37

 [1483 rows x 1 columns],           pax
 arr_city
 AAE        23
 AAL         7
 AAQ         8
 AAR         9
 ABE         8
 ...       ...
 ZQN        28
 ZRH       151
 ZSH         4
 ZUH         0
 ZYL        11

 [1499 rows x 1 columns],           pax
 arr_city
 AAE        17
 AAL         5
 AAQ        11
 AAR        -1
 ABA         1
 ...       ...
 ZQN        10
 ZRH       205
 ZSH         6
 ZVK         2
 ZYL        -3

 [1498 rows x 1 columns],           pax
 arr_city
 AAE         7
 AAL        14
 AAN         2
 AAQ         3
 AAR         4
 ...       ...
 ZQN        13
 ZRH       227
 ZSH         2
 ZTH         0
 ZYL        16

 [1511 rows x 1 columns],           pax
 arr_city
 AAE        11
 AAL        20
 AAQ         7
 AAR         0
 ABE         4
 ...       ...
 ZQN        11
 ZRH       242
 ZSH         4
 ZTH         1
 ZYL        11

 [1471 rows x 1 columns],           pax
 arr_city
 AAB         3
 AAE         7
 AAL        17
 AAQ        10
 AAR         4
 ...       ...
 ZQN        10
 ZRH       189
 ZSH         2
 ZTH         2
 ZYL        -7

 [1491 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        16
 AAQ         5
 AAR         4
 ABE        16
 ...       ...
 ZRH       301
 ZSH         2
 ZTH         0
 ZUH         3
 ZYL        17

 [1446 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11
 ...       ...
 ZOS         2
 ZQN        23
 ZRH       147
 ZSE         3
 ZYL        23

 [1424 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        12
 AAQ        12
 AAR         6
 ABA         1
 ...       ...
 ZSE        -2
 ZSH         4
 ZTH         2
 ZUH         1
 ZYL         8

 [1474 rows x 1 columns],           pax
 arr_city
 AAE         8
 AAH         2
 AAL         4
 AAQ         5
 AAR         3
 ...       ...
 ZSA         1
 ZSH         6
 ZTH         0
 ZVK        -1
 ZYL        37

 [1483 rows x 1 columns],           pax
 arr_city
 AAE        23
 AAL         7
 AAQ         8
 AAR         9
 ABE         8
 ...       ...
 ZQN        28
 ZRH       151
 ZSH         4
 ZUH         0
 ZYL        11

 [1499 rows x 1 columns],           pax
 arr_city
 AAE        17
 AAL         5
 AAQ        11
 AAR        -1
 ABA         1
 ...       ...
 ZQN        10
 ZRH       205
 ZSH         6
 ZVK         2
 ZYL        -3

 [1498 rows x 1 columns],           pax
 arr_city
 AAE         7
 AAL        14
 AAN         2
 AAQ         3
 AAR         4
 ...       ...
 ZQN        13
 ZRH       227
 ZSH         2
 ZTH         0
 ZYL        16

 [1511 rows x 1 columns],           pax
 arr_city
 AAE        11
 AAL        20
 AAQ         7
 AAR         0
 ABE         4
 ...       ...
 ZQN        11
 ZRH       242
 ZSH         4
 ZTH         1
 ZYL        11

 [1471 rows x 1 columns],           pax
 arr_city
 AAB         3
 AAE         7
 AAL        17
 AAQ        10
 AAR         4
 ...       ...
 ZQN        10
 ZRH       189
 ZSH         2
 ZTH         2
 ZYL        -7

 [1491 rows x 1 columns],             pax
 arr_city
 AAE         2.0
 AAL        16.0
 AAQ         5.0
 AAR         4.0
 ABE        16.0
 ...         ...
 ZRH       301.0
 ZSH         2.0
 ZTH         0.0
 ZUH         3.0
 ZYL        17.0

 [1448 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11
 ...       ...
 ZOS         2
 ZQN        23
 ZRH       147
 ZSE         3
 ZYL        23

 [1423 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        12
 AAQ        12
 AAR         6
 ABA         1
 ...       ...
 ZSE        -2
 ZSH         4
 ZTH         2
 ZUH         1
 ZYL         8

 [1474 rows x 1 columns],           pax
 arr_city
 AAE         8
 AAH         2
 AAL         4
 AAQ         5
 AAR         3
 ...       ...
 ZSA         1
 ZSH         6
 ZTH         0
 ZVK        -1
 ZYL        37

 [1483 rows x 1 columns],           pax
 arr_city
 AAE        23
 AAL         7
 AAQ         8
 AAR         9
 ABE         8
 ...       ...
 ZQN        28
 ZRH       151
 ZSH         4
 ZUH         0
 ZYL        11

 [1500 rows x 1 columns],           pax
 arr_city
 AAE        17
 AAL         5
 AAQ        11
 AAR        -1
 ABA         1
 ...       ...
 ZQN        10
 ZRH       205
 ZSH         6
 ZVK         2
 ZYL        -3

 [1498 rows x 1 columns],           pax
 arr_city
 AAE         7
 AAL        14
 AAN         2
 AAQ         3
 AAR         4
 ...       ...
 ZQN        13
 ZRH       227
 ZSH         2
 ZTH         0
 ZYL        16

 [1511 rows x 1 columns],           pax
 arr_city
 AAE        11
 AAL        20
 AAQ         7
 AAR         0
 ABE         4
 ...       ...
 ZQN        11
 ZRH       242
 ZSH         4
 ZTH         1
 ZYL        11

 [1471 rows x 1 columns],           pax
 arr_city
 AAB         3
 AAE         7
 AAL        17
 AAQ        10
 AAR         4
 ...       ...
 ZQN        10
 ZRH       189
 ZSH         2
 ZTH         2
 ZYL        -7

 [1491 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        16
 AAQ         5
 AAR         4
 ABE        16
 ...       ...
 ZRH       301
 ZSH         2
 ZTH         0
 ZUH         3
 ZYL        17

 [1446 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11
 ...       ...
 ZOS         2
 ZQN        23
 ZRH       147
 ZSE         3
 ZYL        23

 [1423 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        12
 AAQ        12
 AAR         6
 ABA         1
 ...       ...
 ZSE        -2
 ZSH         4
 ZTH         2
 ZUH         1
 ZYL         8

 [1474 rows x 1 columns],           pax
 arr_city
 AAE         8
 AAH         2
 AAL         4
 AAQ         5
 AAR         3
 ...       ...
 ZSA         1
 ZSH         6
 ZTH         0
 ZVK        -1
 ZYL        37

 [1483 rows x 1 columns],           pax
 arr_city
 AAE        23
 AAL         7
 AAQ         8
 AAR         9
 ABE         8
 ...       ...
 ZQN        28
 ZRH       151
 ZSH         4
 ZUH         0
 ZYL        11

 [1500 rows x 1 columns],           pax
 arr_city
 AAE        17
 AAL         5
 AAQ        11
 AAR        -1
 ABA         1
 ...       ...
 ZQN        10
 ZRH       205
 ZSH         6
 ZVK         2
 ZYL        -3

 [1498 rows x 1 columns],           pax
 arr_city
 AAE         7
 AAL        14
 AAN         2
 AAQ         3
 AAR         4
 ...       ...
 ZQN        13
 ZRH       227
 ZSH         2
 ZTH         0
 ZYL        16

 [1511 rows x 1 columns],           pax
 arr_city
 AAE        11
 AAL        20
 AAQ         7
 AAR         0
 ABE         4
 ...       ...
 ZQN        11
 ZRH       242
 ZSH         4
 ZTH         1
 ZYL        11

 [1471 rows x 1 columns],           pax
 arr_city
 AAB         3
 AAE         7
 AAL        17
 AAQ        10
 AAR         4
 ...       ...
 ZQN        10
 ZRH       189
 ZSH         2
 ZTH         2
 ZYL        -7

 [1491 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        16
 AAQ         5
 AAR         4
 ABE        16
 ...       ...
 ZRH       301
 ZSH         2
 ZTH         0
 ZUH         3
 ZYL        17

 [1446 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11
 ...       ...
 ZOS         2
 ZQN        23
 ZRH       147
 ZSE         3
 ZYL        23

 [1423 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        12
 AAQ        12
 AAR         6
 ABA         1
 ...       ...
 ZSE        -2
 ZSH         4
 ZTH         2
 ZUH         1
 ZYL         8

 [1474 rows x 1 columns],           pax
 arr_city
 AAE         8
 AAH         2
 AAL         4
 AAQ         5
 AAR         3
 ...       ...
 ZSA         1
 ZSH         6
 ZTH         0
 ZVK        -1
 ZYL        37

 [1483 rows x 1 columns],           pax
 arr_city
 AAE        23
 AAL         7
 AAQ         8
 AAR         9
 ABE         8
 ...       ...
 ZQN        28
 ZRH       151
 ZSH         4
 ZUH         0
 ZYL        11

 [1500 rows x 1 columns],           pax
 arr_city
 AAE        17
 AAL         5
 AAQ        11
 AAR        -1
 ABA         1
 ...       ...
 ZQN        10
 ZRH       205
 ZSH         6
 ZVK         2
 ZYL        -3

 [1498 rows x 1 columns],           pax
 arr_city
 AAE         7
 AAL        14
 AAN         2
 AAQ         3
 AAR         4
 ...       ...
 ZQN        13
 ZRH       227
 ZSH         2
 ZTH         0
 ZYL        16

 [1511 rows x 1 columns],           pax
 arr_city
 AAE        11
 AAL        20
 AAQ         7
 AAR         0
 ABE         4
 ...       ...
 ZQN        11
 ZRH       242
 ZSH         4
 ZTH         1
 ZYL        11

 [1471 rows x 1 columns],           pax
 arr_city
 AAB         3
 AAE         7
 AAL        17
 AAQ        10
 AAR         4
 ...       ...
 ZQN        10
 ZRH       189
 ZSH         2
 ZTH         2
 ZYL        -7

 [1491 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        16
 AAQ         5
 AAR         4
 ABE        16
 ...       ...
 ZRH       301
 ZSH         2
 ZTH         0
 ZUH         3
 ZYL        17

 [1446 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11
 ...       ...
 ZOS         2
 ZQN        23
 ZRH       147
 ZSE         3
 ZYL        23

 [1423 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        12
 AAQ        12
 AAR         6
 ABA         1
 ...       ...
 ZSE        -2
 ZSH         4
 ZTH         2
 ZUH         1
 ZYL         8

 [1474 rows x 1 columns],           pax
 arr_city
 AAE         8
 AAH         2
 AAL         4
 AAQ         5
 AAR         3
 ...       ...
 ZSA         1
 ZSH         6
 ZTH         0
 ZVK        -1
 ZYL        37

 [1483 rows x 1 columns],           pax
 arr_city
 AAE        23
 AAL         7
 AAQ         8
 AAR         9
 ABE         8
 ...       ...
 ZQN        28
 ZRH       151
 ZSH         4
 ZUH         0
 ZYL        11

 [1500 rows x 1 columns],           pax
 arr_city
 AAE        17
 AAL         5
 AAQ        11
 AAR        -1
 ABA         1
 ...       ...
 ZQN        10
 ZRH       205
 ZSH         6
 ZVK         2
 ZYL        -3

 [1498 rows x 1 columns],           pax
 arr_city
 AAE         7
 AAL        14
 AAN         2
 AAQ         3
 AAR         4
 ...       ...
 ZQN        13
 ZRH       227
 ZSH         2
 ZTH         0
 ZYL        16

 [1511 rows x 1 columns],           pax
 arr_city
 AAE        11
 AAL        20
 AAQ         7
 AAR         0
 ABE         4
 ...       ...
 ZQN        11
 ZRH       242
 ZSH         4
 ZTH         1
 ZYL        11

 [1471 rows x 1 columns],           pax
 arr_city
 AAB         3
 AAE         7
 AAL        17
 AAQ        10
 AAR         4
 ...       ...
 ZQN        10
 ZRH       189
 ZSH         2
 ZTH         2
 ZYL        -7

 [1491 rows x 1 columns],           pax
 arr_city
 AAE         2
 AAL        16
 AAQ         5
 AAR         4
 ABE        16
 ...       ...
 ZRH       301
 ZSH         2
 ZTH         0
 ZUH         3
 ZYL        17

 [1446 rows x 1 columns],           pax
 arr_city
 AAE         3
 AAL         5
 AAQ       100
 AAR        10
 ABE         4
 ...       ...
 ZRH       205
 ZSE         0
 ZSH         4
 ZVK         1
 ZYL        16

 [1442 rows x 1 columns],           pax
 arr_city
 AAE         1
 AAL       -19
 AAN         0
 AAQ         4
 AAR        11